name: Run PowerShell Script Daily

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 1:00 PM GMT+3 (10:00 AM UTC) every day
  workflow_dispatch:        # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Run PowerShell Script
      run: |
        pwsh ./activity_check.ps1

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add daycount.txt
        git commit -m "Increment day count"
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
