name: Run PowerShell Script Daily

on:
  schedule:
    - cron: '43 17 * * *'  # Runs at 8:43 PM GMT+3 (which is 5:43 PM UTC) every day
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Run PowerShell Script
      run: |
        pwsh ./activity_check.ps1
