name: Run PowerShell Script Daily

on:
  schedule:
    - cron: '43 17 * * *'  # Automatically runs at 8:43 PM GMT+3 (5:43 PM UTC) every day
  workflow_dispatch:        # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Allow pushing changes back to the repository
        persist-credentials: false
        fetch-depth: 0              # Ensure we have the full history so we can push

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Run PowerShell Script
      run: |
        pwsh ./activity_check.ps1

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add daycount.txt
        git commit -m "Increment day count"
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use the custom token name you set in the repository
